## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
canonifyURLs = "true"

# Local
baseURL = 'samira-the-rogue-gnome.github.io/my-dnd-adventures'
publishDir = "public"
themesDir = "themes"
theme = 'hugo-story'
sectionpagesMenu = 'main'
uglyurls = 'true'

[permalinks]
    [permalinks.section]
    posts = '/posts/'

[build]
  duplicateResourceFiles = false
  noJSConfigInAssets = false
  useResourceCacheWhen = 'fallback'
  [build.buildStats]
    disableClasses = false
    disableIDs = false
    disableTags = false
    enable = false
  [[build.cacheBusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = '(css|styles|scss|sass)'

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

#disableKinds = ["taxonomy", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]
